import { ReactNode } from "react";
import "../styles/index.scss";
export const metadata = {
  title: "Lendsqr assessment",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link href="/imgs/logo.svg" rel="icon" type="image/svg" />
      </head>
      <body>{children}</body>
    </html>
  );
}
